### ISSUE TITLE
[Client] [Attach] Process attach seems to be broken

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#30]
The list of processes is empty, even though I have running java programs.

- Either we support it, and we need to fix it
- Or we decide to not support this anymore, and we remove the entry from the menu

**Comment by jeromecomte** [comment]
Fix committed to develop.

**Comment by dcransac** [comment]
Still doesn't work (see exception down below). Problem was due to the tools.jar File not being on the classpath.

I suggest we do the following :
- only display the Process Attach option _if_ the tools.jar File is found on the classpath.
- document the fact that a JDK's tools.jar needs to be included in the classpath if the user wants to process attach
- by default I do NOT want to force the use to use a JDK, I'd prefer to be JRE-compatible and yet, "error free" / "confusion free"

`
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
	at io.djigger.ui.connectiondialog.AttachConnectionParameters.<init>(AttachConnectionParameters.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at io.djigger.ui.connectiondialog.AgentConnectionDialog.switchPanes(AgentConnectionDialog.java:153)
	at io.djigger.ui.connectiondialog.AgentConnectionDialog.access$100(AgentConnectionDialog.java:37)
	at io.djigger.ui.connectiondialog.AgentConnectionDialog$1.actionPerformed(AgentConnectionDialog.java:100)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 57 more
`

**Comment by dcransac** [comment]
By the way, what did you fix exactly? :D

**Comment by jeromecomte** [comment]
tools.jar has to added explicitly to the classpath (see https://docs.oracle.com/javase/8/docs/technotes/tools/findingclasses.html). I fixed a timing issue that occurred during the connection to the agent. I thought that was the issue you were reporting

**Comment by jeromecomte** [comment]
I've just implemented a feature that checks if tools.jar is available in the classpath. If it is not in the CP an info is displayed to the user telling that tools.jar has to be added to the classpath. If we want to have a specific start script for that case, we could display a more specific info.

**Comment by dcransac** [comment]
Wait a second, maybe I misunderstood something : is the tools.jar file _only_ part of a JDK or is it also shipped with a JRE?

At least I'm not finding it inside the IBM JDK.

So it sounds like your feature was needed indeed. I'll test it and close the issue if it WAI.

**Comment by dcransac** [comment]
WAI
